#!/bin/bash
set -e

if [ ! -d "/data/mysql" ]; then
	echo 'Initializing database'
	mysql_install_db  --user=root --datadir="/data" --rpm
	echo 'Database initialized'
fi

/etc/init.d/mysql start --user=root --datadir="/data"
