#!/bin/bash
set -e

chown -R batman:dccomic /var/lib/mysql
chown -R batman:dccomic /var/run/mariadb
chown -R batman:dccomic /var/log/mariadb

if [ ! -d "/var/lib/mysql/mysql" ]; then
	echo 'Initializing database'
	mysql_install_db --user=batman
	echo 'Database initialized'
fi

mysqld_safe --user=batman
